export type OccasionId = 'festival' | 'wedding' | 'birthday' | 'engagement' | 'anniversary' | 'baby' | 'housewarming' | 'business' | 'religious' | 'party' | 'school' | 'cultural' | 'family' | 'other';
export type TemplateStyle = 'elegant' | 'minimal' | 'traditional' | 'royal' | 'modern' | 'floral' | 'cinematic' | 'cute' | 'colorful' | 'professional' | 'playful' | 'classic' | 'pastel' | 'festive';
export type LanguageCode = 'en' | 'hi' | 'mr' | 'gu' | 'bn' | 'ta' | 'te' | 'kn' | 'ml' | 'pa' | 'or' | 'as' | 'ur' | 'ne';

export interface OccasionInfo {
  id: OccasionId;
  name: string;
  shortName: string;
  icon: string;
  description: string;
  color: string;
  recommendedStyles: TemplateStyle[];
  recommendedEffects: string[];
  recommendedFeatures: string[];
  contentFields: ContentField[];
  defaultContent: Record<string, string>;
  messageSuggestions: { category: string; text: string }[];
}

export interface ContentField { key: string; label: string; placeholder: string; required?: boolean; type?: 'text' | 'date' | 'time' | 'textarea' | 'tel' | 'url'; }

export interface ThemeColors { primary: string; secondary: string; accent: string; background: string; surface: string; text: string; textLight: string; }

export interface TemplateInfo {
  id: string;
  name: string;
  occasion: OccasionId;
  style: TemplateStyle;
  color: string;
  tags: string[];
  description: string;
  image: string;
  accent: string;
  bg: string;
  dark: boolean;
  supportedLanguages: LanguageCode[];
  effects: string[];
  features: string[];
  sampleImages: string[];
  gallery: 'single' | 'polaroid' | 'masonry' | 'cinematic' | 'floating';
  theme: ThemeColors;
  sections: string[];
  defaultContent: Record<string, string>;
  typography: { heading: string; body: string };
  popularity: number;
}

export interface EffectInfo { id: string; name: string; group: string; description: string; icon: string; }
export interface MusicInfo { id: string; name: string; category: string; description: string; }
export interface FeatureInfo { id: string; name: string; description: string; icon: string; }

const wedding = 'https://images.pexels.com/photos/33417236/pexels-photo-33417236.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const birthday = 'https://images.pexels.com/photos/10165858/pexels-photo-10165858.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const baby = 'https://images.pexels.com/photos/33542467/pexels-photo-33542467.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const home = 'https://images.pexels.com/photos/7642034/pexels-photo-7642034.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const business = 'https://images.pexels.com/photos/8555527/pexels-photo-8555527.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const flowers = 'https://images.pexels.com/photos/35568784/pexels-photo-35568784.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const diya = 'https://images.pexels.com/photos/34431714/pexels-photo-34431714.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const family = 'https://images.pexels.com/photos/9345672/pexels-photo-9345672.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const rangoli = 'https://images.pexels.com/photos/34400038/pexels-photo-34400038.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';

export const OCCASIONS: OccasionInfo[] = [
  { id: 'festival', name: 'Festivals', shortName: 'Festival', icon: '✦', description: 'Celebrate traditions, lights and togetherness.', color: '#d3580b', recommendedStyles: ['festive', 'traditional', 'royal'], recommendedEffects: ['diya', 'rangoli', 'shimmer'], recommendedFeatures: ['gallery', 'music', 'share'],
    contentFields: [{ key: 'festivalName', label: 'Festival name', placeholder: 'e.g. Ganpati Festival', required: true }, { key: 'familyName', label: 'Family name', placeholder: 'e.g. The Sharma Family' }, { key: 'date', label: 'Date', type: 'date', required: true }, { key: 'time', label: 'Time', type: 'time' }, { key: 'venue', label: 'Venue', placeholder: 'e.g. Sharma Residence' }, { key: 'address', label: 'Address', placeholder: 'Full address' }, { key: 'message', label: 'Invitation message', type: 'textarea', placeholder: 'Write a heartfelt message...' }],
    defaultContent: { festivalName: 'Ganpati Festival', familyName: 'The Sharma Family', message: 'With the blessings of Lord Ganesha, we invite you to celebrate with us.' },
    messageSuggestions: [{ category: 'Traditional', text: 'With the blessings of the Almighty, we cordially invite you and your family to join our celebration.' }, { category: 'Formal', text: 'We request the pleasure of your company as we celebrate this auspicious occasion.' }, { category: 'Short', text: 'Join us as we celebrate with joy and devotion!' }] },
  { id: 'wedding', name: 'Wedding', shortName: 'Wedding', icon: '♡', description: 'Begin your forever with an invitation as special as your story.', color: '#9f3c5b', recommendedStyles: ['elegant', 'floral', 'royal'], recommendedEffects: ['curtain', 'cinematic', 'petals'], recommendedFeatures: ['rsvp', 'countdown', 'gallery', 'maps'],
    contentFields: [{ key: 'name', label: 'Bride name', placeholder: 'e.g. Ananya', required: true }, { key: 'secondName', label: 'Groom name', placeholder: 'e.g. Aarav', required: true }, { key: 'date', label: 'Wedding date', type: 'date', required: true }, { key: 'time', label: 'Time', type: 'time' }, { key: 'venue', label: 'Venue', placeholder: 'e.g. Grand Palace, Pune' }, { key: 'address', label: 'Address', placeholder: 'Full address' }, { key: 'message', label: 'Wedding message', type: 'textarea', placeholder: 'Write something heartfelt...' }],
    defaultContent: { name: 'Ananya', secondName: 'Aarav', message: 'With hearts full of joy, we invite you to celebrate the beginning of our forever.' },
    messageSuggestions: [{ category: 'Formal', text: 'With hearts full of joy, we invite you to celebrate the beginning of our forever.' }, { category: 'Traditional', text: 'With the blessings of our elders, we cordially invite you to bless us on our wedding day.' }, { category: 'Modern', text: 'We are getting married! Come celebrate love, laughter and new beginnings with us.' }, { category: 'Emotional', text: 'Two hearts, one love, one beautiful beginning. We would be honored to have you with us.' }, { category: 'Short', text: 'Join us as we say "I do"!' }] },
  { id: 'birthday', name: 'Birthday', shortName: 'Birthday', icon: '✧', description: 'Turn another year into a moment everyone remembers.', color: '#e06d56', recommendedStyles: ['playful', 'colorful', 'modern'], recommendedEffects: ['confetti', 'particles', 'zoom'], recommendedFeatures: ['rsvp', 'gallery', 'music'],
    contentFields: [{ key: 'name', label: 'Name', placeholder: 'e.g. Aarav', required: true }, { key: 'age', label: 'Age', placeholder: 'e.g. 25' }, { key: 'date', label: 'Date', type: 'date', required: true }, { key: 'time', label: 'Time', type: 'time' }, { key: 'venue', label: 'Venue', placeholder: 'e.g. Party Hall, Pune' }, { key: 'address', label: 'Address', placeholder: 'Full address' }, { key: 'message', label: 'Birthday message', type: 'textarea', placeholder: 'Write something fun...' }],
    defaultContent: { name: 'Aarav', age: '25', message: 'Join us as we celebrate another beautiful year of memories, laughter and love!' },
    messageSuggestions: [{ category: 'Modern', text: 'Join us as we celebrate another beautiful year of memories, laughter and love!' }, { category: 'Funny', text: 'Cake, candles and chaos — another year older, another year wiser!' }, { category: 'Short', text: 'Let us party! You are invited!' }, { category: 'Emotional', text: 'Every year with you is a gift. Come celebrate with us!' }] },
  { id: 'engagement', name: 'Engagement', shortName: 'Engagement', icon: '◇', description: 'Share the promise before the forever.', color: '#c58a3e', recommendedStyles: ['elegant', 'minimal', 'floral'], recommendedEffects: ['golden', 'petals', 'cinematic'], recommendedFeatures: ['rsvp', 'gallery', 'maps'],
    contentFields: [{ key: 'name', label: 'First name', placeholder: 'e.g. Priya', required: true }, { key: 'secondName', label: 'Second name', placeholder: 'e.g. Rohan', required: true }, { key: 'date', label: 'Date', type: 'date', required: true }, { key: 'time', label: 'Time', type: 'time' }, { key: 'venue', label: 'Venue', placeholder: 'e.g. Hotel Grand' }, { key: 'address', label: 'Address', placeholder: 'Full address' }, { key: 'message', label: 'Message', type: 'textarea', placeholder: 'Write something heartfelt...' }],
    defaultContent: { name: 'Priya', secondName: 'Rohan', message: 'Two souls, one promise. Join us as we begin our journey together.' },
    messageSuggestions: [{ category: 'Formal', text: 'Two souls, one promise. Join us as we begin our journey together.' }, { category: 'Romantic', text: 'Love brought us together, and now we make it forever. Celebrate with us!' }, { category: 'Short', text: 'We are getting engaged! Come share the joy!' }] },
  { id: 'anniversary', name: 'Anniversary', shortName: 'Anniversary', icon: '♡', description: 'Celebrate the beautiful chapters you have written together.', color: '#bd5a62', recommendedStyles: ['floral', 'classic', 'cinematic'], recommendedEffects: ['petals', 'polaroid', 'zoom'], recommendedFeatures: ['gallery', 'music', 'story'],
    contentFields: [{ key: 'name', label: 'First name', placeholder: 'e.g. Raj', required: true }, { key: 'secondName', label: 'Second name', placeholder: 'e.g. Simran', required: true }, { key: 'years', label: 'Years together', placeholder: 'e.g. 25' }, { key: 'date', label: 'Date', type: 'date', required: true }, { key: 'time', label: 'Time', type: 'time' }, { key: 'venue', label: 'Venue', placeholder: 'e.g. Garden Restaurant' }, { key: 'message', label: 'Message', type: 'textarea', placeholder: 'Write something heartfelt...' }],
    defaultContent: { name: 'Raj', secondName: 'Simran', years: '25', message: 'Through every season, our love has only grown. Celebrate with us!' },
    messageSuggestions: [{ category: 'Emotional', text: 'Through every season, our love has only grown. Celebrate with us!' }, { category: 'Classic', text: 'A love story worth celebrating. Join us as we mark another beautiful year.' }, { category: 'Short', text: 'Cheers to us! Come celebrate!' }] },
  { id: 'baby', name: 'Baby & Naming', shortName: 'Baby', icon: '○', description: 'Welcome a little wonder with warmth and joy.', color: '#d68c8c', recommendedStyles: ['cute', 'pastel', 'floral'], recommendedEffects: ['floating', 'particles', 'polaroid'], recommendedFeatures: ['rsvp', 'gallery', 'message'],
    contentFields: [{ key: 'name', label: 'Baby name', placeholder: 'e.g. Little Star', required: true }, { key: 'parents', label: 'Parents', placeholder: 'e.g. Priya & Rohan' }, { key: 'date', label: 'Date', type: 'date', required: true }, { key: 'time', label: 'Time', type: 'time' }, { key: 'venue', label: 'Venue', placeholder: 'e.g. Home' }, { key: 'address', label: 'Address', placeholder: 'Full address' }, { key: 'message', label: 'Message', type: 'textarea', placeholder: 'Write something sweet...' }],
    defaultContent: { name: 'Little Star', parents: 'Priya & Rohan', message: 'A little wonder has arrived! Join us to welcome our bundle of joy.' },
    messageSuggestions: [{ category: 'Sweet', text: 'A little wonder has arrived! Join us to welcome our bundle of joy.' }, { category: 'Short', text: 'Tiny toes, endless love. Come meet our little one!' }, { category: 'Emotional', text: 'Our hearts are full. Come celebrate the newest member of our family!' }] },
  { id: 'housewarming', name: 'Housewarming', shortName: 'New Home', icon: '⌂', description: 'Open the doors to a new beginning.', color: '#6f8d62', recommendedStyles: ['minimal', 'traditional', 'modern'], recommendedEffects: ['diya', 'golden', 'reveal'], recommendedFeatures: ['maps', 'rsvp', 'calendar'],
    contentFields: [{ key: 'name', label: 'Family name', placeholder: 'e.g. The Iyer Family', required: true }, { key: 'date', label: 'Date', type: 'date', required: true }, { key: 'time', label: 'Time', type: 'time' }, { key: 'venue', label: 'New home', placeholder: 'e.g. Bungalow 12, Pune' }, { key: 'address', label: 'Address', placeholder: 'Full address' }, { key: 'message', label: 'Message', type: 'textarea', placeholder: 'Write something warm...' }],
    defaultContent: { name: 'The Iyer Family', message: 'We have a new home! Come bless us as we begin a new chapter.' },
    messageSuggestions: [{ category: 'Traditional', text: 'We have a new home! Come bless us as we begin a new chapter.' }, { category: 'Modern', text: 'New address, new memories. Come celebrate our new home with us!' }, { category: 'Short', text: 'Housewarming party! You are invited!' }] },
  { id: 'business', name: 'Business & Corporate', shortName: 'Business', icon: '▦', description: 'Invite people to your next big milestone.', color: '#2c6670', recommendedStyles: ['professional', 'modern', 'minimal'], recommendedEffects: ['reveal', 'zoom', 'parallax'], recommendedFeatures: ['maps', 'rsvp', 'contact'],
    contentFields: [{ key: 'name', label: 'Business name', placeholder: 'e.g. Sharma Enterprises', required: true }, { key: 'ownerName', label: 'Owner name', placeholder: 'e.g. R. Sharma' }, { key: 'date', label: 'Opening date', type: 'date', required: true }, { key: 'time', label: 'Time', type: 'time' }, { key: 'venue', label: 'Location', placeholder: 'e.g. Shop 5, Market Road' }, { key: 'address', label: 'Address', placeholder: 'Full address' }, { key: 'contact', label: 'Contact', type: 'tel', placeholder: 'Phone number' }, { key: 'message', label: 'Business message', type: 'textarea', placeholder: 'Write your message...' }],
    defaultContent: { name: 'Sharma Enterprises', ownerName: 'R. Sharma', message: 'We are delighted to invite you to our grand opening!' },
    messageSuggestions: [{ category: 'Professional', text: 'We are delighted to invite you to our grand opening!' }, { category: 'Formal', text: 'You are cordially invited to the inauguration of our new establishment.' }, { category: 'Short', text: 'Grand opening! Come celebrate with us!' }] },
  { id: 'religious', name: 'Puja & Religious', shortName: 'Religious', icon: '◈', description: 'Share sacred moments with your community.', color: '#b36a25', recommendedStyles: ['traditional', 'festive', 'classic'], recommendedEffects: ['diya', 'rangoli', 'shimmer'], recommendedFeatures: ['maps', 'schedule', 'music'],
    contentFields: [{ key: 'name', label: 'Event name', placeholder: 'e.g. Satyanarayan Puja', required: true }, { key: 'familyName', label: 'Family name', placeholder: 'e.g. The Deshmukh Family' }, { key: 'date', label: 'Date', type: 'date', required: true }, { key: 'time', label: 'Time', type: 'time' }, { key: 'venue', label: 'Venue', placeholder: 'e.g. Deshmukh Residence' }, { key: 'address', label: 'Address', placeholder: 'Full address' }, { key: 'message', label: 'Message', type: 'textarea', placeholder: 'Write a sacred message...' }],
    defaultContent: { name: 'Satyanarayan Puja', familyName: 'The Deshmukh Family', message: 'With devotion in our hearts, we invite you to join us in prayer and celebration.' },
    messageSuggestions: [{ category: 'Traditional', text: 'With devotion in our hearts, we invite you to join us in prayer and celebration.' }, { category: 'Formal', text: 'We seek your presence and blessings on this sacred occasion.' }, { category: 'Short', text: 'Join us for a blessed celebration!' }] },
  { id: 'party', name: 'Party', shortName: 'Party', icon: '✦', description: 'Bring your favorite people together.', color: '#8a5a9a', recommendedStyles: ['colorful', 'playful', 'modern'], recommendedEffects: ['confetti', 'particles', 'zoom'], recommendedFeatures: ['rsvp', 'music', 'gallery'],
    contentFields: [{ key: 'name', label: 'Party name', placeholder: 'e.g. Saturday Night Party', required: true }, { key: 'date', label: 'Date', type: 'date', required: true }, { key: 'time', label: 'Time', type: 'time' }, { key: 'venue', label: 'Venue', placeholder: 'e.g. Club House' }, { key: 'address', label: 'Address', placeholder: 'Full address' }, { key: 'message', label: 'Message', type: 'textarea', placeholder: 'Write something fun...' }],
    defaultContent: { name: 'Saturday Night Party', message: 'Good music, great food, amazing people. Be there!' },
    messageSuggestions: [{ category: 'Fun', text: 'Good music, great food, amazing people. Be there!' }, { category: 'Short', text: 'Party time! Do not miss it!' }, { category: 'Modern', text: 'Let us make tonight unforgettable. You are invited!' }] },
  { id: 'school', name: 'School & College', shortName: 'School', icon: '▱', description: 'Mark the moments that shaped a generation.', color: '#47768d', recommendedStyles: ['modern', 'playful', 'minimal'], recommendedEffects: ['parallax', 'polaroid', 'zoom'], recommendedFeatures: ['gallery', 'rsvp', 'timeline'],
    contentFields: [{ key: 'name', label: 'Event name', placeholder: 'e.g. Class of 2026 Reunion', required: true }, { key: 'date', label: 'Date', type: 'date', required: true }, { key: 'time', label: 'Time', type: 'time' }, { key: 'venue', label: 'Venue', placeholder: 'e.g. School Campus' }, { key: 'address', label: 'Address', placeholder: 'Full address' }, { key: 'message', label: 'Message', type: 'textarea', placeholder: 'Write something nostalgic...' }],
    defaultContent: { name: 'Class of 2026 Reunion', message: 'Let us relive the golden days. Come reconnect and celebrate!' },
    messageSuggestions: [{ category: 'Nostalgic', text: 'Let us relive the golden days. Come reconnect and celebrate!' }, { category: 'Short', text: 'Reunion time! See you there!' }, { category: 'Fun', text: 'Same friends, new memories. Let us get the gang back together!' }] },
  { id: 'cultural', name: 'Cultural Event', shortName: 'Cultural', icon: '◎', description: 'Gather around art, heritage and shared expression.', color: '#7b5a42', recommendedStyles: ['traditional', 'colorful', 'modern'], recommendedEffects: ['rangoli', 'particles', 'parallax'], recommendedFeatures: ['schedule', 'maps', 'gallery'],
    contentFields: [{ key: 'name', label: 'Event name', placeholder: 'e.g. Kala Utsav', required: true }, { key: 'date', label: 'Date', type: 'date', required: true }, { key: 'time', label: 'Time', type: 'time' }, { key: 'venue', label: 'Venue', placeholder: 'e.g. Community Hall' }, { key: 'address', label: 'Address', placeholder: 'Full address' }, { key: 'message', label: 'Message', type: 'textarea', placeholder: 'Write something inspiring...' }],
    defaultContent: { name: 'Kala Utsav', message: 'Come celebrate the colors of our culture and heritage!' },
    messageSuggestions: [{ category: 'Inspiring', text: 'Come celebrate the colors of our culture and heritage!' }, { category: 'Formal', text: 'We cordially invite you to an evening of art, music and tradition.' }, { category: 'Short', text: 'A celebration of culture awaits!' }] },
  { id: 'family', name: 'Family Function', shortName: 'Family', icon: '⌘', description: 'Make every family gathering feel extraordinary.', color: '#638156', recommendedStyles: ['classic', 'floral', 'minimal'], recommendedEffects: ['polaroid', 'petals', 'reveal'], recommendedFeatures: ['gallery', 'maps', 'message'],
    contentFields: [{ key: 'name', label: 'Function name', placeholder: 'e.g. Family Get-Together', required: true }, { key: 'familyName', label: 'Family name', placeholder: 'e.g. The Patil Family' }, { key: 'date', label: 'Date', type: 'date', required: true }, { key: 'time', label: 'Time', type: 'time' }, { key: 'venue', label: 'Venue', placeholder: 'e.g. Patil Farmhouse' }, { key: 'address', label: 'Address', placeholder: 'Full address' }, { key: 'message', label: 'Message', type: 'textarea', placeholder: 'Write something warm...' }],
    defaultContent: { name: 'Family Get-Together', familyName: 'The Patil Family', message: 'Family is everything. Come celebrate togetherness with us!' },
    messageSuggestions: [{ category: 'Warm', text: 'Family is everything. Come celebrate togetherness with us!' }, { category: 'Short', text: 'Family time! See you all there!' }, { category: 'Emotional', text: 'No matter how far we go, family brings us home. Join us!' }] },
  { id: 'other', name: 'Other Celebration', shortName: 'Other', icon: '✧', description: 'Your occasion is unique. Your invitation should be too.', color: '#726c61', recommendedStyles: ['modern', 'minimal', 'elegant'], recommendedEffects: ['reveal', 'shimmer', 'zoom'], recommendedFeatures: ['rsvp', 'gallery', 'share'],
    contentFields: [{ key: 'name', label: 'Occasion name', placeholder: 'e.g. Farewell Party', required: true }, { key: 'date', label: 'Date', type: 'date', required: true }, { key: 'time', label: 'Time', type: 'time' }, { key: 'venue', label: 'Venue', placeholder: 'e.g. Community Center' }, { key: 'address', label: 'Address', placeholder: 'Full address' }, { key: 'message', label: 'Message', type: 'textarea', placeholder: 'Write your message...' }],
    defaultContent: { name: 'A Special Celebration', message: 'You are warmly invited to join us for a celebration to remember!' },
    messageSuggestions: [{ category: 'General', text: 'You are warmly invited to join us for a celebration to remember!' }, { category: 'Short', text: 'Come celebrate with us!' }] },
];

const occasionImages: Record<OccasionId, string> = { festival: diya, wedding, birthday, engagement: flowers, anniversary: flowers, baby, housewarming: home, business, religious: diya, party: birthday, school: business, cultural: rangoli, family, other: flowers };
const styleColors: Record<TemplateStyle, { accent: string; bg: string; dark: boolean; theme: ThemeColors; typography: { heading: string; body: string } }> = {
  elegant: { accent: '#9f3c5b', bg: 'linear-gradient(150deg,#fff8f5,#f0d8d6)', dark: false, theme: { primary: '#9f3c5b', secondary: '#c58a3e', accent: '#d4a23a', background: '#fff8f5', surface: '#f0d8d6', text: '#3d1f2a', textLight: '#7a5560' }, typography: { heading: "'Marcellus', serif", body: "'Plus Jakarta Sans', sans-serif" } },
  minimal: { accent: '#6d8062', bg: 'linear-gradient(150deg,#fbfaf5,#e9eee6)', dark: false, theme: { primary: '#6d8062', secondary: '#8fa683', accent: '#b0c4a8', background: '#fbfaf5', surface: '#e9eee6', text: '#2a3d28', textLight: '#5a6d58' }, typography: { heading: "'Marcellus', serif", body: "'Plus Jakarta Sans', sans-serif" } },
  traditional: { accent: '#b36a25', bg: 'linear-gradient(150deg,#fff6e2,#e8c487)', dark: false, theme: { primary: '#b36a25', secondary: '#d4a23a', accent: '#e0b95a', background: '#fff6e2', surface: '#e8c487', text: '#4a2f12', textLight: '#7a5530' }, typography: { heading: "'Marcellus', serif", body: "'Plus Jakarta Sans', sans-serif" } },
  royal: { accent: '#c0933b', bg: 'linear-gradient(150deg,#122f2b,#1b4d43)', dark: true, theme: { primary: '#c0933b', secondary: '#e0b95a', accent: '#d4a23a', background: '#122f2b', surface: '#1b4d43', text: '#f5e7c0', textLight: '#c0a878' }, typography: { heading: "'Marcellus', serif", body: "'Plus Jakarta Sans', sans-serif" } },
  modern: { accent: '#2c6670', bg: 'linear-gradient(150deg,#edf8f6,#bddbd8)', dark: false, theme: { primary: '#2c6670', secondary: '#4794a0', accent: '#6bb5be', background: '#edf8f6', surface: '#bddbd8', text: '#1a3f45', textLight: '#4a7078' }, typography: { heading: "'Marcellus', serif", body: "'Plus Jakarta Sans', sans-serif" } },
  floral: { accent: '#bd5a62', bg: 'linear-gradient(150deg,#fff6f5,#f3d6da)', dark: false, theme: { primary: '#bd5a62', secondary: '#d68c8c', accent: '#e0b0b0', background: '#fff6f5', surface: '#f3d6da', text: '#4a1f25', textLight: '#7a4550' }, typography: { heading: "'Marcellus', serif", body: "'Plus Jakarta Sans', sans-serif" } },
  cinematic: { accent: '#e0b95a', bg: 'linear-gradient(150deg,#171717,#493426)', dark: true, theme: { primary: '#e0b95a', secondary: '#c0933b', accent: '#d4a23a', background: '#171717', surface: '#2a2018', text: '#f5e7c0', textLight: '#a89870' }, typography: { heading: "'Marcellus', serif", body: "'Plus Jakarta Sans', sans-serif" } },
  cute: { accent: '#d68c8c', bg: 'linear-gradient(150deg,#fffafa,#f7dfe6)', dark: false, theme: { primary: '#d68c8c', secondary: '#e8b0b0', accent: '#f0c8c8', background: '#fffafa', surface: '#f7dfe6', text: '#4a2a2a', textLight: '#7a5555' }, typography: { heading: "'Marcellus', serif", body: "'Plus Jakarta Sans', sans-serif" } },
  colorful: { accent: '#e06d56', bg: 'linear-gradient(150deg,#fff3d6,#f6b38b)', dark: false, theme: { primary: '#e06d56', secondary: '#ef9a6e', accent: '#f5c098', background: '#fff3d6', surface: '#f6b38b', text: '#4a2a1a', textLight: '#7a5540' }, typography: { heading: "'Marcellus', serif", body: "'Plus Jakarta Sans', sans-serif" } },
  professional: { accent: '#2c6670', bg: 'linear-gradient(150deg,#eef4f5,#c7dbe0)', dark: false, theme: { primary: '#2c6670', secondary: '#4794a0', accent: '#6bb5be', background: '#eef4f5', surface: '#c7dbe0', text: '#1a3f45', textLight: '#4a7078' }, typography: { heading: "'Marcellus', serif", body: "'Plus Jakarta Sans', sans-serif" } },
  playful: { accent: '#8a5a9a', bg: 'linear-gradient(150deg,#f7eff9,#e3ccef)', dark: false, theme: { primary: '#8a5a9a', secondary: '#a878b8', accent: '#c8a8d8', background: '#f7eff9', surface: '#e3ccef', text: '#3a1f4a', textLight: '#6a4a7a' }, typography: { heading: "'Marcellus', serif", body: "'Plus Jakarta Sans', sans-serif" } },
  classic: { accent: '#7b5a42', bg: 'linear-gradient(150deg,#fbf6eb,#e5d3b5)', dark: false, theme: { primary: '#7b5a42', secondary: '#a8856a', accent: '#c4a888', background: '#fbf6eb', surface: '#e5d3b5', text: '#3a2a1a', textLight: '#6a5a4a' }, typography: { heading: "'Marcellus', serif", body: "'Plus Jakarta Sans', sans-serif" } },
  pastel: { accent: '#b989a3', bg: 'linear-gradient(150deg,#fffaf7,#eadcf0)', dark: false, theme: { primary: '#b989a3', secondary: '#d4a8b8', accent: '#e8c8d8', background: '#fffaf7', surface: '#eadcf0', text: '#4a2a3a', textLight: '#7a5a6a' }, typography: { heading: "'Marcellus', serif", body: "'Plus Jakarta Sans', sans-serif" } },
  festive: { accent: '#d3580b', bg: 'linear-gradient(150deg,#4b2017,#9a4b24)', dark: true, theme: { primary: '#d3580b', secondary: '#ef7111', accent: '#e0b95a', background: '#4b2017', surface: '#6a3520', text: '#fce8c8', textLight: '#d4a878' }, typography: { heading: "'Marcellus', serif", body: "'Plus Jakarta Sans', sans-serif" } },
};

const templateNames: Record<OccasionId, string[]> = { festival: ['Marigold Light', 'Diya Glow', 'Rangoli Evening', 'Sacred Gold'], wedding: ['The Royal Vow', 'Garden Ceremony', 'Rose Promise', 'Velvet Baraat'], birthday: ['The Big Day', 'Color Pop', 'Cake & Confetti', 'Birthday Story'], engagement: ['The Promise', 'Golden Ring', 'Forever Begins'], anniversary: ['Our Chapters', 'Rose Letter', 'Still Us'], baby: ['Little Wonder', 'Sweet Arrival', 'Tiny Toes'], housewarming: ['New Beginnings', 'Open Doors', 'Griha Pravesh'], business: ['The Launch', 'Modern Milestone', 'Business Bloom'], religious: ['Sacred Light', 'Blessed Gathering', 'Divine Darshan'], party: ['After Hours', 'Let us Celebrate', 'The Guest List'], school: ['The Reunion', 'Class Of', 'Next Chapter'], cultural: ['Living Heritage', 'The Showcase', 'Kala'], family: ['Together', 'Family Album', 'Homecoming'], other: ['One Beautiful Day', 'The Invitation', 'Gather Together'] };
const stylesByOccasion: Record<OccasionId, TemplateStyle[]> = { festival: ['festive','traditional','royal','cinematic'], wedding: ['elegant','floral','royal','cinematic'], birthday: ['playful','colorful','modern','cute'], engagement: ['elegant','minimal','floral'], anniversary: ['floral','classic','cinematic'], baby: ['cute','pastel','floral'], housewarming: ['minimal','traditional','modern'], business: ['professional','modern','minimal'], religious: ['traditional','festive','classic'], party: ['colorful','playful','modern'], school: ['modern','playful','minimal'], cultural: ['traditional','colorful','modern'], family: ['classic','floral','minimal'], other: ['modern','minimal','elegant'] };

const defaultSections = ['cover', 'greeting', 'event', 'gallery', 'message', 'venue', 'rsvp', 'closing'];

export const TEMPLATES: TemplateInfo[] = Object.entries(templateNames).flatMap(([occasion, names]) => names.map((name, index) => { const occasionId = occasion as OccasionId; const styles = stylesByOccasion[occasionId]; const style = styles[index % styles.length]; const theme = styleColors[style]; const occasionInfo = OCCASIONS.find((o) => o.id === occasionId); return { id: `${occasion}-${index + 1}`, name, occasion: occasionId, style, color: theme.accent, tags: [style, occasionInfo?.shortName ?? occasion, index === 0 ? 'Popular' : 'New'], description: `${name} — a ${style} invitation made for your ${occasionInfo?.name.toLowerCase()}.`, image: occasionImages[occasionId], accent: theme.accent, bg: theme.bg, dark: theme.dark, supportedLanguages: ['en','hi','mr','gu','bn','ta','te','kn','ml','pa','ur'], effects: occasionInfo?.recommendedEffects ?? [], features: occasionInfo?.recommendedFeatures ?? [], sampleImages: [occasionImages[occasionId], family], gallery: index % 2 ? 'masonry' : 'cinematic', theme: theme.theme, sections: defaultSections, defaultContent: occasionInfo?.defaultContent ?? {}, typography: theme.typography, popularity: index === 0 ? 90 : 60 + index * 10 }; }));

export const EFFECTS: EffectInfo[] = [
  { id: 'diya', name: 'Diya Reveal', group: 'Opening', description: 'A warm glow reveals your celebration.', icon: '◉' }, { id: 'curtain', name: 'Curtain Reveal', group: 'Opening', description: 'A graceful reveal for a grand beginning.', icon: '▥' }, { id: 'golden', name: 'Golden Glow', group: 'Text', description: 'Elegant light sweeps across your words.', icon: '✦' }, { id: 'rangoli', name: 'Rangoli Reveal', group: 'Opening', description: 'A colorful pattern blooms into view.', icon: '◈' }, { id: 'particles', name: 'Particle Reveal', group: 'Background', description: 'Subtle particles bring the page to life.', icon: '⋯' }, { id: 'parallax', name: 'Parallax', group: 'Scroll', description: 'Layers move gently as guests explore.', icon: '↕' }, { id: 'polaroid', name: 'Polaroid', group: 'Photo', description: 'Memories arrive like keepsakes.', icon: '▣' }, { id: 'zoom', name: 'Cinematic Zoom', group: 'Transition', description: 'A cinematic focus on every moment.', icon: '⌕' }, { id: 'petals', name: 'Floating Petals', group: 'Background', description: 'A soft trail of petals follows the story.', icon: '❋' }, { id: 'confetti', name: 'Confetti', group: 'Ending', description: 'A joyful burst to close the invitation.', icon: '✧' }, { id: 'shimmer', name: 'Golden Shimmer', group: 'Text', description: 'A celebratory shimmer for special details.', icon: '◇' }, { id: 'reveal', name: 'Letter Reveal', group: 'Opening', description: 'Your message appears one thoughtful line at a time.', icon: 'Aa' },
];
export const MUSIC: MusicInfo[] = ['Devotional','Wedding','Birthday','Romantic','Festive','Celebration','Instrumental','Traditional','Modern'].map((category) => ({ id: category.toLowerCase(), name: `${category} mood`, category, description: `A ${category.toLowerCase()} soundscape for your invitation.` }));
export const FEATURES: FeatureInfo[] = [
  ['rsvp','RSVP','Let guests confirm their attendance.','◌'], ['countdown','Countdown','Build anticipation to the big day.','◷'], ['maps','Google Maps','Make the venue easy to find.','⌖'], ['schedule','Event Schedule','Share the moments and timings.','☷'], ['gallery','Photo Gallery','Tell your story through memories.','▧'], ['video','Video','Add a personal video message.','▶'], ['music','Music','Set the mood with a soundtrack.','♫'], ['message','Guest Message','Give guests a way to leave wishes.','✎'], ['share','Share Button','Make your invitation easy to pass on.','↗'], ['calendar','Add To Calendar','Help guests save the date.','▣'], ['contact','Contact Button','Make reaching you effortless.','◉'], ['gift','Digital Gift','Add a gift or donation link.','◇'], ['dress','Dress Code','Share the look for the celebration.','⌁'], ['story','Couple Story','Tell the story behind the moment.','♡'], ['timeline','Event Timeline','Show the journey in a beautiful flow.','↠'], ['thankyou','Thank You Page','End with a warm personal note.','✦'],
].map(([id, name, description, icon]) => ({ id, name, description, icon }));
export const STYLE_OPTIONS: TemplateStyle[] = ['elegant','minimal','traditional','royal','modern','floral','cinematic','cute','colorful','professional','playful','classic','pastel','festive'];
export const LANGUAGES_SUPPORTED: { code: LanguageCode; name: string; native: string; dir?: 'ltr' | 'rtl' }[] = [ ['en','English','English'],['hi','Hindi','हिन्दी'],['mr','Marathi','मराठी'],['gu','Gujarati','ગુજરાતી'],['bn','Bengali','বাংলা'],['ta','Tamil','தமிழ்'],['te','Telugu','తెలుగు'],['kn','Kannada','ಕನ್ನಡ'],['ml','Malayalam','മലയാളം'],['pa','Punjabi','ਪੰਜਾਬੀ'],['or','Odia','ଓଡ଼ିଆ'],['as','Assamese','অসমীয়া'],['ur','Urdu','اردو','rtl'],['ne','Nepali','नेपाली'] ].map(([code,name,native,dir]) => ({ code: code as LanguageCode, name: name as string, native: native as string, dir: dir as 'rtl' | 'ltr' | undefined }));
export const WHATSAPP_NUMBER = '918208146862';
export const FAQS = [{ q: 'What is a digital invitation?', a: 'A beautiful, interactive invitation that guests can open and share from one memorable link.' }, { q: 'Can I create an invitation for any occasion?', a: 'Yes. FestiveLink is designed for weddings, birthdays, festivals, family functions, business events and every celebration in between.' }, { q: 'Can I add my own photos, video and music?', a: 'Yes. Your builder lets you personalize the experience with your own memories and preferences.' }, { q: 'Which languages are supported?', a: 'You can create invitations in English and a wide range of Indian languages, including bilingual invitations.' }, { q: 'Can I save and continue later?', a: 'Yes. Save your design on this device and restore it whenever you are ready.' }, { q: 'How do guests receive the invitation?', a: 'You receive a shareable FestiveLink that works beautifully on phones and can be sent through WhatsApp or any other channel.' }];
